### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by rpelisse** [ansible-middleware/wildfly#105]
##### SUMMARY

We've released a few articles on the Red Hat Developer blog  about this collection ([Automate and deploy a JBoss EAP cluster with Ansible](https://developers.redhat.com/articles/2022/02/08/automate-and-deploy-jboss-eap-cluster-ansible), [Update and upgrade JBoss EAP with Ansible](https://developers.redhat.com/articles/2023/04/04/update-and-upgrade-jboss-eap-ansible) and [How to easily deploy JBoss EAP on Azure](https://developers.redhat.com/articles/2022/08/17/how-ansible-simplifies-jboss-eap-deployment-azure)). However, the documentation of the collection itself is pretty lacking. It would be nice to try to enhance it, based on the content of the articles.

##### ISSUE TYPE
 - Feature Idea

**Comment by samccann** [comment]
Hi @rpelisse .. I see the collection has its [own docsite](https://ansiblemiddleware.com/wildfly/main/). Is the goal here to add to that docsite with some of the blog post content?
 I also see some of the docs (md) are visible in [beta-galaxy.ansible.com](https://beta-galaxy.ansible.com/ui/repo/published/middleware_automation/wildfly/docs/developing/).  Anything we put in .rst for these docs improvements won't show up on galaxy.  

We could alternately put all the new blog-based content in .md and then it would show up on both, but I don't know how cleanly it would show in Galaxy (beta) as that has a limited set  of md it supports (and afaik, no way to order the files ).

What's your preference here?

**Comment by rpelisse** [comment]
I was more thinking enriching the main README and the README in the role with information that might be only in the articles. Also maybe restructure those README (if needed).

@guidograzioli any thoughts?

**Comment by guidograzioli** [comment]
About beta-galaxy, I didn't know it existed :P  Looks _very_ similar to private automation hub, though? We already try to avoid rst (using md instead) for being able to show on the hub. Only the changelog automation generates rst and we convert it with pandoc to md anyway when we do upstream->downstream transformations

**Comment by guidograzioli** [comment]
About the blogs content I have been thinking, we could even add completely new pages under docs/, and we link them in antsibull-doc on a new dedicated section, (like ie. "usage"?)

Example:

* we have a blog that talks about supplying yaml config to the extension, we would have:
   * roles/wildfly_systemd/README.md has only the doc for the parameters (`wildfly_enable_yml_config`, `wildfly_yml_configs`). The generated table from the spec2readme script could even be enough
   * wildfly/README.md has a paragraph called "configuring with yaml extension", which has a couple of lines telling the extension can be used via the collection
   * docs/yaml_extension.md (under the toc:: usage), describes how to use like in the blob
  
Same could be done for instance for: 
* offline installs
* patching
* cluster configuration
* adding the jdbc driver
* ...

**Comment by samccann** [comment]
Discussed in the DaWGs meeting, we can take two phases to this work:

Phase 1 - review the existing readme files and open a PR or two to edit or restructure etc to make them clear and separate any user information from developer/contributor information

Phase 2 - review the blog posts listed above and incorporate some of that information in the appropriate readme.

Note - these should happen in the above sequence but don't need to be the same PR or even the same person doing each.
