### ISSUE TITLE
Downstream: yml config is dependent on patch being applied

### ISSUE THREAD

**Issue by rpelisse** [ansible-middleware/wildfly#114]
##### SUMMARY

Downstream, the use of yml config is conditional on a first patch being applied. Which means, for instance, that it's impossible to use YAML config with 7.4 or 8.0.0.Beta (version without a patch to apply to). 

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```

```

##### COLLECTION VERSION

```

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by rpelisse** [comment]
@guidograzioli FYI

**Comment by guidograzioli** [comment]
I think @RanabirChakraborty already addresses that on #110
