### ISSUE TITLE
wildfly_firewalld documentation (README) is missing

### ISSUE THREAD

**Issue by InfoSec812** [ansible-middleware/wildfly#126]
##### SUMMARY
The default variables for wildfly_firewalld are not listed/explained in the README for that role

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
N/A

##### COLLECTION VERSION
All

##### STEPS TO REPRODUCE
N/A

##### EXPECTED RESULTS
The three variables in the defaults.yaml should be listed and explained.

##### ACTUAL RESULTS
No docs available

**Comment by rpelisse** [comment]
Fixed by https://github.com/ansible-middleware/wildfly/pull/139
