### ISSUE TITLE
wildfly_systemd - port offset calculation

### ISSUE THREAD

**Issue by aushacker** [ansible-middleware/wildfly#13]
Firstly, thanks for the hard work in getting this project up and going. I have a requirement that this automation solves nicely.

However, I am unable to understand why the formula calculating jboss.socket.binding.port-offset is:
`100 * (instance_id - wildfly_port_range_offset)`

As it stands setting:
```
    vars:
      wildfly_port_range_offset: -1
```
results in an actual port offset of 100 and server ports will be numbered 8180, 8280, 8380 etc.

I am curious as to:

1. Why is a negative number used?
2. Why the offset is automatically scaled by 100?
3. Why the first server is offset by 100, not 0?

I would have thought that:
```
    vars:
      wildfly_port_range_offset: 100
```
results in an actual port offset of 100 and server ports will be numbered 8080, 8180, 8280 etc. That is, the formula should be:
`instance_id * wildfly_port_range_offset`

Please tell me. What I am not understanding?

**Comment by rpelisse** [comment]
To be honest, this is something we need to fix, it's basically technical debt, carrying over moving this logic out of our [Flange](github.com/ansible-middleware/flange) demo to this collection.

So I guess the answer to:

> Please tell me. What I am not understanding?

... is : I'm a moron :) 

Ideally, the variable should be defined in the role's defaults/main.yml to be zero:

`wildfly_port_range_offset: 0
`
And this should lead to the first instance to be bound against 8080. (which is used by Keycloak in the Flange's demo...).
