### ISSUE TITLE
Remove dependency on python-requests module

### ISSUE THREAD

**Issue by InfoSec812** [ansible-middleware/wildfly#141]
##### SUMMARY
My customer's RHEL 7/8 systems did not have the `python(3)-requests` module installed and they are having python version issues for installing the requests module with the right version of python. It would be really helpful if we did not depend on the requests module

##### ISSUE TYPE
 - Feature Idea

**Comment by sabre1041** [comment]
Since this dependency is part of the common collection, [issue](https://github.com/ansible-middleware/common/issues/15) created there
