### ISSUE TITLE
Set pid file for systemd to `/var/run/{{ instance }}` or allow for custom pid file location

### ISSUE THREAD

**Issue by InfoSec812** [ansible-middleware/wildfly#164]
##### SUMMARY
When running Wildfly/JBoss on a system with SELinux enabled, the pid file needs to be located in `/var/run` or you must create/apply a custom SELinux module to allow systemd to maintain the pid file. Because of this, I would like to propose one or both of the following options:

- Allow for a custom pid file location when using the `wildfly_systemd` role
- Default the pid file location to `/var/run`

##### ISSUE TYPE
 - Feature Idea

**Comment by rpelisse** [comment]
@RanabirChakraborty are you working on this? If not, please assign the issue to me!

**Comment by RanabirChakraborty** [comment]
@rpelisse Thanks for the ping :D I haven't started working on it, But I'll look into it this week.
