### ISSUE TITLE
Remove wildly_subs

### ISSUE THREAD

**Issue by istraka** [ansible-middleware/wildfly#169]
##### SUMMARY
Remove `wildfly_subs` role per https://docs.google.com/document/d/1pOL6xIADZ_G_lRTIuYvTpdeTuOxgPS6PAvLYQH8s2hk/edit?disco=AAAA6HsH93s

AFAIK, this should eventually get into EAP Ansible collection.

**Comment by rpelisse** [comment]
@istraka The role is [removed](https://github.com/ansible-middleware/janus/blob/main/playbooks/eap.yml#L34) when this collection is transformed to become EAP.
