### ISSUE TITLE
Provide documentation for wildfly_migration role

### ISSUE THREAD

**Issue by istraka** [ansible-middleware/wildfly#170]
##### SUMMARY
Documentation for [wildfly_migration](https://github.com/ansible-middleware/wildfly/tree/main/roles/wildfly_migration) role seems to be copied from [wildfly_subs](https://github.com/ansible-middleware/wildfly/tree/main/roles/wildfly_subs) role. Can it be updated? Would it automatically get into EAP7 Ansible collection?

**Comment by rpelisse** [comment]
Fixed by #182
