### ISSUE TITLE
Provide documentation for wildfly_prospero role

### ISSUE THREAD

**Issue by istraka** [ansible-middleware/wildfly#171]
##### SUMMARY
Can a documentation for [wildfly_prospero](https://github.com/ansible-middleware/wildfly/tree/main/roles/wildfly_prospero) role be updated?

There are no variables mentioned in the Readme.

Will it eventually get into EAP7 Ansible collection?

**Comment by rpelisse** [comment]
When @spyrkob has finalized the role, we'll use a script to generate all this documentation (well, with placeholder). I'll keep this issue open until then, so we don't forget! 

> Will it eventually get into EAP7 Ansible collection?

We won't have a EAP7 collection distinct from EAP8, it will be the same collection for both version. However, Prospero will not work for EAP7.

**Comment by istraka** [comment]
OK, we will also need to have this info in https://console.redhat.com/ansible/automation-hub/repo/published/redhat/eap/content/role/eap_prospero/ .

**Comment by rpelisse** [comment]
Yes, the documentation for wildfly_prospero will be transformed to become the one of eap_prospero.

**Comment by rpelisse** [comment]
Fixed by #182
