### ISSUE TITLE
Document missing variables from systemd example

### ISSUE THREAD

**Issue by istraka** [ansible-middleware/wildfly#174]
##### SUMMARY
Following variables / defaults are not documented:

- wildfly_config_name
- service_systemd_env_file
- service_systemd_conf_file

**Comment by rpelisse** [comment]
As wildfly_config_name is only used in wildfly_systemd role, I've renamed it to wildfly_systemd_config_name to follow the suggested convention.

**Comment by rpelisse** [comment]
Fixed by #182

**Comment by rpelisse** [comment]
@guidograzioli as I've renamed one var, I think we need to mark this as major change, right?
