### ISSUE TITLE
wildfly_install - possible excess variables

### ISSUE THREAD

**Issue by aushacker** [ansible-middleware/wildfly#18]
Question, are the following variables in wildfly_install required:
1. wildfly_config_base
2. wildfly_jvm_memory_min
3. wildfly_jvm_memory_max
4. wildfly_jvm_metaspace_size?

Are these used during wildfly_install or are they needed by wildfly_systemd?

**Comment by rpelisse** [comment]
I don't think they are required (we provided default). Maybe you can check, but indeed, they most likely belong to _systemd and need to be move there.
