### ISSUE TITLE
Allow configuration update from YML file using middleware_automation.wildfly collection

### ISSUE THREAD

**Issue by fmarchioni** [ansible-middleware/wildfly#209]
Since WildFly application server also support configuration updates via yml files [1], it would be great if WildFly roles from middleware_automation.wildfly would allow an idempotent update of the configuration using a yml file.

My attempt currently produces the following output:

```
ansible-playbook verify.yml --ask-become-pass
BECOME password: 
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'

PLAY [verify] ******************************************************************

TASK [middleware_automation.wildfly.wildfly_validation : Validating arguments against arg spec 'main'] ***
ok: [localhost]

TASK [middleware_automation.wildfly.wildfly_validation : Ensure required parameters are provided.] ***
ok: [localhost]

TASK [middleware_automation.wildfly.wildfly_validation : Ensure user wildfly were created.] ***
ok: [localhost]

TASK [middleware_automation.wildfly.wildfly_validation : Validate state of user: wildfly] ***
ok: [localhost]

TASK [middleware_automation.wildfly.wildfly_validation : Ensure user wildfly were created.] ***
ok: [localhost]

TASK [middleware_automation.wildfly.wildfly_validation : Validate state of group: wildfly.] ***
ok: [localhost]

TASK [middleware_automation.wildfly.wildfly_validation : Verify server's installation directory] ***
included: /home/francesco/.ansible/collections/ansible_collections/middleware_automation/wildfly/roles/wildfly_validation/tasks/verify_owner_and_group.yml for localhost

TASK [middleware_automation.wildfly.wildfly_validation : Ensure installation directory.] ***
ok: [localhost]

TASK [middleware_automation.wildfly.wildfly_validation : Ensure installation directory.] ***
fatal: [localhost]: FAILED! => {
    "assertion": "wildfly_home_status.stat.exists",
    "changed": false,
    "evaluated_to": false,
    "msg": "wildfly installation folder is in a wrong state"
}

PLAY RECAP *********************************************************************
localhost                  : ok=8    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 
```

I've created the following playbooks to reproduce the issue:
- wildfly.yml (installation - OK)
- verify ( update- KO)

I'm unable to attach them here, but I've got them here: [2]
Thanks

[1] https://www.wildfly.org/news/2022/04/26/YAML-configuration-extension/
[2] https://github.com/fmarchioni/mastertheboss/tree/master/ansible/wildfly

**Comment by rpelisse** [comment]
@fmarchioni The support for using YAML config is already there, there is even a [molecule scenario for it](https://github.com/ansible-middleware/wildfly/tree/main/molecule/yaml_config_validation). The usage is documented as part of the [wildfly_systemd](https://github.com/ansible-middleware/wildfly/blob/main/roles/wildfly_systemd/README.md) role.

**Comment by rpelisse** [comment]
@fmarchioni Let us know if you need more information!

**Comment by fmarchioni** [comment]
Thanks for your reply @rpelisse indeed I needed to include also the wildfly_systemd role to have the YAML files included in the config update. I'll close this issue then.
