### ISSUE TITLE
Not a single var file present.

### ISSUE THREAD

**Issue by RanabirChakraborty** [ansible-middleware/wildfly#21]
I was going through the roles, and it seems like we don't have a single var file to control all the vars from a single file itself. Just for an example if we want to change the `wildfly-version` we need to change it in every possible place.
Do we have any plan for that or this was made to be like this.

**Comment by guidograzioli** [comment]
Hello Ranabir, we are documenting the variables currently in a PR.
wildfly_version is only used by the wildfly_install role and has default 26.0.0.Final
https://github.com/ansible-middleware/wildfly/blob/main/roles/wildfly_install/defaults/main.yml#L2

**Comment by guidograzioli** [comment]
The vars are used like that in example playbook and the molecule playbook in order to keep it self-contained; in a consumer playbook, all the needed overrides are supposed to go in the inventory group_vars
