### ISSUE TITLE
Fix up recurrent failure of the Prospero scenario (probably by releasing Prospero 1.3.0)

### ISSUE THREAD

**Issue by rpelisse** [ansible-middleware/wildfly#238]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```

```

##### COLLECTION VERSION

```

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by spyrkob** [comment]
(hopefully) fixed by https://github.com/ansible-middleware/wildfly/pull/239
