### ISSUE TITLE
wildfly_user and wildfly_group are not defined in wildfly_driver module

### ISSUE THREAD

**Issue by eirisdg** [ansible-middleware/wildfly#76]
##### SUMMARY
wildfly_user and wildfly_group are not defined in wildfly_driver module

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```

```

##### COLLECTION VERSION

```
1.1.0
```

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

wildfly_user and wildfly_group must be set in order to be used in the main task

##### ACTUAL RESULTS

```

```

**Comment by guidograzioli** [comment]
Fixed by #77
