### ISSUE TITLE
WILDFLY_SERVER_CONFIG must be set to standalone.xml by default

### ISSUE THREAD

**Issue by eirisdg** [ansible-middleware/wildfly#78]
##### SUMMARY

In wildfly_systemd role, the wfly.conf.j2 file sets some vars, but I don't se sense in one of them:
`WILDFLY_SERVER_CONFIG={{ instance_name }}.xml`

If you don't set any other instance than the default, it will pont the systemd service to the config file `wildfly.xml`, when by default, the config file is standalone.xml.

Shouldn't be somethink like this?
`WILDFLY_SERVER_CONFIG={{ wildfly_config_base}}`

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible [core 2.13.1]
```

##### COLLECTION VERSION

```
1.1.0
```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by guidograzioli** [comment]
That is not really the case; ```wildfly_config_base``` sets which of the stock xml configuration files to use (among standalone, standalone-ha, standalone-full-ha...) to [create the actual](https://github.com/ansible-middleware/wildfly/blob/main/roles/wildfly_systemd/tasks/main.yml#L99) configuration. That config file, if nothing else is defined, [defaults to](https://github.com/ansible-middleware/wildfly/blob/main/roles/wildfly_systemd/tasks/main.yml#L71) "wildfly.xml"

**Comment by eirisdg** [comment]
Ok, you're right, I didn't see the copy file from standalone.
