### ISSUE TITLE
yaml configuration extension should accept templates

### ISSUE THREAD

**Issue by guidograzioli** [ansible-middleware/wildfly#84]
##### SUMMARY

It is possible to pass files along the wildfly_systemd yml config extension feature; templates should be supported too

##### ISSUE TYPE
 - Feature Idea

**Comment by RanabirChakraborty** [comment]
@guidograzioli Can I work on it?

**Comment by guidograzioli** [comment]
Sure go ahead; the idea is the yaml configuration file list treats every path as a template (it shoudl strip the .j2 extension from input files if present)
